# [[manager.prepend_keymap]]
# on   = "<Enter>"
# run  = "plugin smart-enter"
# desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<Space>"
run = [ "toggle"]
desc = "Toggle the current selection state"  # Dont Move to next selection

