[opener]
edit = [
	{ run = 'nvim "$@"', desc = "Open in Neovim", block = true, for = "unix" },
	{ run = 'code . "$@"', desc = "Open in VSCode(Workspace)", block = true, for = "unix" },
	{ run = 'code "$@"', desc = "Open in VSCode(File only)", block = true, for = "unix" },
    { run = 'nvim -O "$@"', desc = "Split files in Neovim", block = true, for = "unix" },
    { run = 'nvim -d "$@"', desc = "Diff files in Neovim", block = true, for = "unix" },
    { run = 'code --diff "$@"', desc = "Diff files in VSCode", block = true, for = "unix" },

	{ run = 'nvim %*', block = true,  desc = "Open in Neovim",   for = "windows" },
	{ run = 'code . %*', block = true,  desc = "Open in VSCode(Workspace)",   for = "windows" },
	{ run = 'code %*', block = true,  desc = "Open in VSCode(Workspace)",   for = "windows" },
    { run = 'nvim -O "$@"', desc = "Split files in Neovim", block = true, for = "windows" },
    { run = 'nvim -d "$@"', desc = "Diff files in Neovim", block = true, for = "windows" },
    { run = 'code --diff "$@"', desc = "Diff files in VSCode", block = true, for = "windows" },
]
