return {
    -- {
    --     'folke/todo-comments.nvim',
    --     event = 'VimEnter',
    --     dependencies = { 'nvim-lua/plenary.nvim', 'folke/snacks.nvim' },
    --     opts = { signs = false },
    --     keys = {
    --         {
    --             ']t',
    --             function()
    --                 require('todo-comments').jump_next()
    --             end,
    --             desc = 'Next Todo Comment',
    --         },
    --         {
    --             '[t',
    --             function()
    --                 require('todo-comments').jump_prev()
    --             end,
    --             desc = 'Previous Todo Comment',
    --         },
    --         {
    --             '<leader>st',
    --             function()
    --                 require('snacks').picker.todo_comments()
    --             end,
    --             desc = 'Todo',
    --         },
    --         {
    --             '<leader>sT',
    --             function()
    --                 require('snacks').picker.todo_comments { keywords = { 'TODO', 'FIX', 'FIXME' } }
    --             end,
    --             desc = 'Todo/Fix/Fixme',
    --         },
    --     },
    -- },
}
